# Generated by Django 5.2.5 on 2025-08-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('social_id', models.CharField(max_length=100)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('kakao', 'Kakao'), ('naver', 'Naver'), ('github', 'GitHub')], max_length=20)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('profile_image', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'unique_together': {('social_id', 'provider')},
            },
        ),
    ]
