# Generated by Django 5.2.5 on 2025-08-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_provider_alter_user_provider'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('ci', 'provider')},
        ),
        migrations.AddField(
            model_name='user',
            name='ci',
            field=models.CharField(default='', help_text='CI - 소셜 플랫폼의 고유 식별자', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='di',
            field=models.CharField(default='', help_text='DI - 우리 서비스의 고유 사용자 식별자', max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='user',
            name='social_id',
        ),
    ]
